import type { Metadata } from "next";

import "./globals.css";
import { ReactNode } from 'react';
import ThemeProvider from '../components/ThemeProvider'







export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    
    <html lang="en">
      <body
        className="bg-(--bg) text-(--text) font-sans"
      >
        <ThemeProvider >
        {children}
        </ThemeProvider>
      </body>
  </html>
  
  );
}
