import type { Metadata } from "next";

import "./globals.css";
import { ReactNode } from 'react';
import ThemeProvider from '../components/ThemeProvider'
import { Toaster } from "react-hot-toast";







export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    
    <html lang="en">
      <body
        className="font-sans antialiased"
      >
        <ThemeProvider >
        {children}
        <Toaster position="top-right" />
        </ThemeProvider>
      </body>
  </html>
  
  );
}
